site_name: Kaka's Docs
nav:
        - Home: index.md
        - Example: trang_1.md
        - MicroPython: micropython.md
        - AWS Notes: aws_notes.md 
        - About: about.md
theme: readthedocs

